### ISSUE TITLE
Node launch from docker-compose missing file

### ISSUE THREAD

**Issue by vadimicus** [MinterTeam/minter-go-node#154]
Actually - fail to run node from docker-compose.

Just followed this [instruction](https://minter-go-node.readthedocs.io/en/dev/install.html#install-minter)

Error looks like this
````
Pulling minter (minterteam/minter:0.7.0)...
ERROR: manifest for minterteam/minter:0.7.0 not found

````
Docker compose file looks like this
````
version: "3.4"
services:
  minter:
    image: minterteam/minter:0.7.0
    volumes:
      - ~/.minter:/minter
    ports:
      - "8841:8841"
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8841/api/status"]
      interval: 5s
      timeout: 5s
      retries: 3
````
